-- Run this entire file in Supabase SQL Editor.

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  telegram_chat_id text not null,
  telegram_message_id bigint not null,
  title text not null default 'New Anime Update',
  content text default '',
  category text default 'Anime Update',
  image_url text default '',
  message_url text default '',
  published_at timestamptz not null default now(), is_published boolean not null default true, created_at timestamptz not null default now(), unique (telegram_chat_id, telegram_message_id) );

create table if not exists public.channels (
  id bigint generated by default as identity primary key,
  name text not null,
  url text not null,
  is_main boolean not null default false,
  is_active boolean not null default true,
  sort_order int not null default 0
);

alter table public.posts enable row level security;
alter table public.channels enable row level security;

create policy "public can read published posts"
on public.posts for select
to anon, authenticated using (is_published = true);

create policy "public can read active channels"
on public.channels for select
to anon, authenticated using (is_active = true);

-- Replace these examples with your real public Telegram channel links.
insert into public.channels (name,url,is_main,sort_order)
values
('Main Channel','https://t.me/your_channel',true,1),
('Updates','https://t.me/your_updates',false,2)
on conflict do nothing;
